language: java
sudo: required

jdk:
  - oraclejdk8
  
dist: trusty
 
 # safelist
branches:
  only:
    - master

install:
  - cd desapp-grupoC1F-backend && mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
